In [1]:
import numpy as np
print(np.__version__) #shows the version of the numpy
print(np.show_config()) #shows the build configuration of the numpy

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/grgsu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/grgsu/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/grgsu/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\

In [2]:
print(np.info(np.add)) #shows the information regarding the add fucntion

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [5]:
example = np.arange(9).reshape((3,3))

In [6]:
example

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
print(np.all(example)) #the all() function evaluates to true where there is 
#non-zero elements otherwise it will be false. To evaluate whether there is 
#non-zero elements you can use any().

False


In [9]:
example2 = np.array([1, 7, 13, 105])

In [10]:
example2

array([  1,   7,  13, 105])

In [11]:
print("%d bytes" % (example2.size*example2.itemsize)) 
#calcaulate the size of the memory occupied by the array.

16 bytes


In [17]:
example3 = np.array([np.zeros(10), np.ones(10), np.full((10),5)])
#creates an array of 10 zeros, 10 ones, 10 fives.

In [18]:
example3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [21]:
example4 = np.arange(30,71)
#creates an array of integers from 30 to 70.

In [22]:
example4

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

In [25]:
example5 = np.arange(30,71,2)
#creates an array from 30 to 70 but only with even numbers.

In [26]:
example5

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])

In [32]:
example6 = np.random.normal(0,1,1)
#generates a random number between 0 and 1.

In [33]:
example6

array([-0.47071162])

In [34]:
example7 = np.random.randn(15)
#gnerates an array of 15 random numbers from a standard normal distribution.

In [35]:
example7

array([ 0.98733872, -1.22481854,  0.57730438, -0.64423334,  0.4161621 ,
       -1.67209787,  0.69283274, -0.16227834,  0.81608084, -0.63967806,
        1.97012379, -0.04961431, -0.36746201,  0.98411272,  0.52006912])

In [36]:
example8 = np.arange(15,56)
print(example8[1:-1])
#creats a vectoir with values ranging from 15 to 55 and prints all values 
#except the first and last.

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [39]:
example9 = np.arange(12).reshape((3,4))
#creates a 3x4 array and iterate over it.

In [42]:
for x in np.nditer(example9):
    print(x,end=" ")
#iterates the array example9 and lists all the values in the array.

0 1 2 3 4 5 6 7 8 9 10 11 

In [43]:
example10 = np.arange(0, 20)

In [44]:
example10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [45]:
example10[(example10>=9) & (example10<=15)] *= -1
#changes the sign of the numbers in the range from 9 to 15.

In [46]:
example10

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,  -9, -10, -11, -12,
       -13, -14, -15,  16,  17,  18,  19])

In [47]:
example11 = np.array([1, 2, 3, 4, 5])
example12 = np.array([6, 7, 8, 9, 10])

In [48]:
example11*example12
#gives the product of array example 11 and example 12.

array([ 6, 14, 24, 36, 50])

In [51]:
example13 = np.arange(10, 22).reshape((3,4))
#creates a array of 3x4 matrix with values from 10 to 21.

In [52]:
example13

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [55]:
example13.shape
#outputs the number of rows and columns of a given matrix.

(3, 4)

In [67]:
example14 = np.ones((10,10))
print(example14)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [71]:
example14[1:-1, 1:-1] = 0
#changes the values inside the border to 0.

In [72]:
example14

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [74]:
example15 = np.zeros((5,5))
print(example15)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [77]:
example15[0, 0] = 1
example15[1, 1] = 2
example15[2, 2] = 3
example15[3, 3] = 4
example15[4, 4] = 5
#changes the values at the given indexs to the given values.
#can be done using np.diag([1, 2, 3, 4, 5])

In [78]:
example15

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [79]:
example16 = np.arange(25).reshape((5,5))
print(example16)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [86]:
np.sum(example16)
#computes the sum of the arrray.

300

In [84]:
example16.sum(axis=0)
#computes the sum of the columns.

array([50, 55, 60, 65, 70])

In [85]:
example16.sum(axis=1)
#computes the sum of the rows.

array([ 10,  35,  60,  85, 110])

In [87]:
x = np.array([4,5])
y = np.array([7, 10])
print(np.dot(x,y))
#computes the inner product of two given vectors.

78


In [5]:
orginal_list = [12.23, 13.32, 100, 36.32]

In [7]:
arr = np.array(orginal_list) #creates an array from the input orginal_list.
print(arr)

[ 12.23  13.32 100.    36.32]


In [8]:
example17 = np.arange(2,11).reshape((3,3))
print(example17)
#creates a 3x3 matrix with values ranging from 2 to 10.

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [10]:
example18 = np.zeros(10)
print(example18)
example18[6] = 11
print(example18)
#creates a null vector of size 10 and updates sixth value to 11.

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [12]:
example19 = np.arange(12,38)
print(example19)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [15]:
example19 = example19[::-1]
print(example19)
#reverses the array.

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [16]:
original_array = [1,2,3,4]

In [20]:
arr2 = np.array((original_array), dtype = np.float64)
print(arr2)
arr2.dtype
#converts the original list into array with data type being float64.

[1. 2. 3. 4.]


dtype('float64')

In [21]:
my_tuple = ([8, 4, 6], [1, 2, 3])
arr3 = np.asarray(my_tuple)
print(arr3)
#converts the tuple into an array.

[[8 4 6]
 [1 2 3]]


In [23]:
example20 = np.array([10, 20, 30])
example20 = np.append(example20, [[40, 50, 60], [70, 80, 90]])
print(example20)
#add the values at the end of the array example20.

[10 20 30 40 50 60 70 80 90]


In [26]:
example21 = np.empty((3, 3)) #creates an empty array.
print(example21)
example22 = np.full((3,3),6) #creates a full array with values 6.
print(example22)

[[0.000e+000 0.000e+000 0.000e+000]
 [0.000e+000 0.000e+000 2.925e-321]
 [0.000e+000 0.000e+000 0.000e+000]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [32]:
example23 = np.array([0, 12, 45.21, 34, 99.91])
print(example23)

[ 0.   12.   45.21 34.   99.91]


In [33]:
example23 = (5/9)*(example23-32)
print("In celsius, the values are ", example23)
#coverts the Fahrenheit temperature values to celsius.

In celsius, the values are  [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [36]:
x1 = np.sqrt([1+0j])
y1 = np.sqrt([0+1j])
print(x1.real) #prints the real parts of an array of complex numbers.
print(y1.real)
print(x1.imag) #prints the imaginary parts of an arry of complex numbers. 
print(y1.imag)

[1.]
[0.70710678]
[0.]
[0.70710678]


In [38]:
example24 = np.array([1, 2, 3], dtype=np.float64)
print(example24.size) #size of the array
print(example24.itemsize) #length of one array elements in bytes
print(example24.nbytes) #total bytes consumed by the elements of the array

3
8
24


In [41]:
arr4 = np.array([0, 10, 20, 40, 60])
arr5 = np.array([0, 40])
np.in1d(arr4, arr5)
#checks whether the elements in arr4 is present in arr5.

array([ True, False, False,  True, False])

In [42]:
arr6 = np.array([0, 10, 20, 40, 60])
arr7 = np.array([10, 30, 40])
np.intersect1d(arr6, arr7)
#computes the common values betweeen array 6 and 7.

array([10, 40])

In [49]:
arr8 = np.array([10, 10, 20, 20, 30, 30])
np.unique(arr8)
#finds the unique values in array 8.

array([10, 20, 30])

In [50]:
arr9 = ([0, 10, 20, 40, 60, 80])
arr10 = ([10, 30, 40, 50, 70, 90])
np.setdiff1d(arr9, arr10)
#find the set difference of two arrays.

array([ 0, 20, 60, 80])

In [54]:
arr11 = np.array([0, 10, 20, 40, 60, 80])
arr12 = np.array([10, 30, 40, 50, 70])
np.setxor1d(arr11, arr12) #finds the set exclusive-or of two arrays.

array([ 0, 20, 30, 50, 60, 70, 80])

In [55]:
np.union1d(arr11, arr12) #finds the union of two arrays of unique values.

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [59]:
array13 = np.array([1, 2, 3, 4])
array13 = np.tile(array13, 2)
print(array13)
#repeats the array 2 times. Uses the function np.tile.

[1 2 3 4 1 2 3 4]


In [61]:
arr14 = np.array([[1,2],[3,4]])
print(np.repeat(arr14, 2))
#repeats elements of an array.

[1 1 2 2 3 3 4 4]


In [63]:
arr15 = np.array([1, 2, 3, 4, 5, 6])
print(np.argmax(arr15))
print(np.argmin(arr15))
#print the index of the maximun and minimum value in an array.

5
0


In [68]:
arr16 = np.array([1, 2])
arr17 = np.array([4, 5])
print(arr16>arr17)
print(arr16>=arr17)
print(arr16<arr17)
print(arr16<=arr17)
#compares the elements inside the array and gives a boolean array

[False False]
[False False]
[ True  True]
[ True  True]


In [72]:
arr18 = np.array([[4, 6],[2,1]])
print(arr18)
print(np.sort((arr18),axis=0)) #sort the elements along the first axis.
print(np.sort((arr18),axis=1)) #sorts the elements along the last axis.

[[4 6]
 [2 1]]
[[2 1]
 [4 6]]
[[4 6]
 [1 2]]


In [79]:
arr19 = np.array([[0, 10, 20], [20,30,40]])
print(arr19)
arr20 = arr19[arr19>10] #outputs the values that are bigger than 10.
print(arr20)
print(np.nonzero(arr19>10)) #shows the indices of the elements that are 
#bigger than 10.

[[ 0 10 20]
 [20 30 40]]
[20 20 30 40]
(array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [85]:
arr20 = np.ones((6,1))
print(arr20)
arr20 = arr20.reshape((2,3))
print(arr20)
#changes the dimensions of an array from (6,1) to (2,3).

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [87]:
arr21 = np.array([[10, 20, 30], [20, 40, 50]])
print(arr21)
arr22 = np.ravel(arr21)
print(arr22)
#creates a contiguous flattened array.

[[10 20 30]
 [20 40 50]]
[10 20 30 20 40 50]


In [90]:
arr23 = np.linspace(2.5, 6.5,30)
print(arr23)
#creates a 1-D array of 30 evenly spaced elements between 2.5 and 6.5. You 
#do similar things with log scale. The function used is 
#np.logspace(range,number of elements, endpoint=False).

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [91]:
arr24 = np.array([[2,4,6],[6,8,10]])
print(arr24[0][2])
#prints the element 6 from the array arr24.

6


In [97]:
arr25 = np.array([[1,2,3]])
arr26 = arr25.T
print(arr26)
#swaps the axes of the array.

[[1]
 [2]
 [3]]


In [101]:
arr27 = np.array([[0,1,3],[5,7,9]])
arr28 = np.array([[0,2,4],[6,8,10]])
print(arr27)
print(arr28)
arr29 = np.concatenate((arr27,arr28),1) #joins a sequence of arrays along an
#existing axis. The number 1 in this example is an axis along with the arrays
#will be joined.
print(arr29)

[[0 1 3]
 [5 7 9]]
[[ 0  2  4]
 [ 6  8 10]]
[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [105]:
arr30 = np.arange(1,15)
print(arr30)
print(np.split(arr30,[2,6]))
#splits the array. arr30 @ 2 and 6.

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [107]:
arr31 = np.arange(16).reshape((4,4))
print(arr31)
print(np.hsplit(arr31,[2,6]))
#splits the 4x4 array into 2 arrays along the 2 axis. hsplit is equivalent
#to split with axis =1, the array is always split along the second axis 
#regardless of the array dimensions. 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int32)]


In [110]:
arr32 = np.array([[0,10,20],[20,30,40]])
print(arr32)
print(np.count_nonzero(arr32))
#counts the number of non-zero elements in the array.

[[ 0 10 20]
 [20 30 40]]
5


In [113]:
arr33 = np.arange(1, 100)
arr34 = arr33[(arr33%3 == 0)| (arr33%5 == 0)]
print(arr34)
print(arr34.sum())
#Creates an array where the elements are multiple of 3 and 5 and then finds 
#the sum of the elements.

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [2]:
arr35 = np.ones((5,5,5))
print(arr35)
#creates a 5x5x5 cube of 1's.

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [6]:
arr36 = np.arange(12).reshape((3,4))
arr36 = arr36*3
print(arr36)
#creates an array of (3,4) shape and multiplies every element valye by 3.

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [12]:
arr37 = np.array([1,2,3,4])
arr38 = np.array(["Red","Green","White","Orange"])
arr39 = np.array([12.20,15,20,40])
result = np.core.records.fromarrays([arr37, arr38, arr39], names="a,b,c")
print(result)
#creates a record of array from a (flat) list of arrays.

[(1, 'Red', 12.2) (2, 'Green', 15. ) (3, 'White', 20. )
 (4, 'Orange', 40. )]


In [15]:
arr40 = np.arange(6).reshape((3,2))
print(arr40)
print(arr40.tolist())
#changes the NumPy array to list.

[[0 1]
 [2 3]
 [4 5]]
[[0, 1], [2, 3], [4, 5]]


In [20]:
arr41 = np.arange(9).reshape(3,3)
print(arr41)
print(arr41[:,0])
print(arr41[:,1])
print(arr41[:,2])
#acess the array by columns.

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 3 6]
[1 4 7]
[2 5 8]


In [21]:
arr42 = np.array([[10,20,30],[40,50,60]])
arr43 = np.array([[100],[200]])
print(np.append(arr42, arr43, axis=1))
#adds an extra column to a Numpy array. 

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [3]:
#NumPy Linear Algebra
arr44 = np.arange(9).reshape((3,3))
arr45 = np.arange(10,19).reshape((3,3))
print(arr44*arr45)
#computes the multiplication of two given matrixes.

[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]


In [4]:
ex25 = [[1,0],[0,1]]
ex26 = [[1,2],[3,4]]
ex27 = np.outer(ex25,ex26)
print(ex27)
#computes the outer product of two vectors.

[[1 2 3 4]
 [0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]


In [5]:
ex28 = np.cross(ex25,ex26)
ex29 = np.cross(ex26,ex25)
print(ex28)
print(ex29)
#computes the cross product of the vectors ex25 and ex26. 

[ 2 -3]
[-2  3]


In [7]:
ex30 = np.arange(16).reshape((4,4))
print(ex30)
print(np.linalg.det(ex30))
#computes the determinant of a given square array. 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-2.9582283945787796e-30
